### ISSUE TITLE
Empty Values

### ISSUE THREAD

**Issue by ToddGeorgeKelly** [maael/temtem-api#10]
Just a suggestion as this isn't really a 'bug'. 

I noticed there are certain cases where the value is unknown. Currently the API handles these inconsistently, likely because it is just literally giving you the information found from the wiki. But making a consistent way to handle these cases could be helpful. Otherwise anyone who uses the API will have to handle the problem on their end. 

Examples of what I am talking about:

**In the KnownTemTemSpecies:**
`"locations": []  `
//This is handled well as an empty array implies that the value is unknown
`"types": ["Unknown"] `
// 'Unknown, not being a TemTem type could be left out in favor of an empty array

```
{
    "number": 2,
    "name": "Oree",
    "stage": 1,
    "levels": "+? Levels"
}
```
//This is normally an integer but occasionally a String because of this particular issue

```
{
    "number": 3,
    "name": "Zaobian",
    "stage": 2
}
```
//In the same TemTem evolution tree, the "levels" value is absent since it doesn't hav an evolutionary step after it. So maybe the tree items that contain a levels value of "+? Levels" could be replaced with a 'null'? I found the value was either an Int, "?", or "+Trading / 25 Levels" So maybe an int or 'null' on the levels value and some boolean value for if trading in needed? Not sure.

```
"locations": [
      {
        "location": "Giant Banyan",
        "island": "Omninesia",
        "frequency": "Common",
        "level": "?"
      },
      {
        "location": "Mokupuni Dojo",
        "island": "Omninesia",
        "frequency": "Gift",
        "level": "35"
      },
```
//Another example where the API users could likely expect an Int or 'null' value only to find a string.

Anyyyway, I hope I am not overstepping with this suggestion and want to express nothing but gratitude that you've even made this. You're the best!

**Comment by maael** [comment]
Not overstepping at all, and thanks for the kind words! :smile:

Just to address your points in order:

### Unknown Type
The `Unknown` type is a special case for [Raignet](https://temtem.gamepedia.com/Raignet) and [Valiar](https://temtem.gamepedia.com/Valiar), Temtem we have some info on but not everything (including typing). At the moment this is the string `"Unknown"` to explicitly mark it as unknown rather than failed to get from the API, and to allow mapping over the `types` for the icons (though writing this I see the Unknown type icon is at [/images/icons/types/UnknownType.png](https://temtem-api.mael.tech/images/icons/types/UnknownType.png), not [/images/icons/types/Unknown.png](https://temtem-api.mael.tech/images/icons/types/Unknown.png) like I was expecting, I'll have to fix that.) It looks like this:

![Unknown Type Icon](https://temtem-api.mael.tech/images/icons/types/UnknownType.png)

Let me know what you think about this though, with the explanation, as I'm not sure about this approach. Maybe it is just better to provide an empty array if we don't know the typing.

### Evolution Tidying

Thanks for digging this out! The temtem object shape is pretty complicated, and the only one I haven't written a typecheck for yet, so these inconsistencies can get through. Your suggestions sound like a good idea! I'll take a look, and see how I can tidy it up, and will let you know when I have so you can take a look/let me know what you think.

**Comment by ToddGeorgeKelly** [comment]
OMG you are so hot rn, ha you fixed so much, honestly I am soooooo god damn grateful for your work. 

Well haha my point of view may be a selfish one since I am strictly coming from the point of trying to parse and decode the JSON files. 

My general rule of thumb is to try to throw a JSON file into an auto parser like [this one](https://app.quicktype.io) before going in and digging into the data myself. It usually does a good job of pointing out cases where decoding the data is unnecessarily complicated. 

**TYPES & EMPTY VALUES**
Keeping the 'types'  limited to only the currently existing types makes it so people decoding the data returned from the API don't have to make a special 'unknown' type in what will likely be an enum of types.  The problem comes if they introduce something beyond this 'unknown' type, whatever it is, it will still be technically unknown as it it's 'type', it just won't be called 'unknown'. The result would be that you will then have two 'types' to express an unknown value. This might occur when they finally introduce an additional type(or two) to the game. The people using your API will have to have something to handle an unexpected input anyway until they update their own code to represent that. 
Again, though, this isn't 'right', just my opinion. haha.

**EMPTY STRINGS vs NULL**
Again opinions here ha. I personally think that null is more useful 'in general' since handling an empty string is still handling a value. You just have to now interpret the value as empty rather than just receiving an optional. Having an empty string is sort of like having a 0 value in an Integer, which is not an accurate value since to represent that the value is actually blank. 


**EVOLUTION LEVEL**
Seriously thank you for this one, I noticed the 'trading' boolean you added as well. SOOO hot! Thank you!
Before you fixed the levels in the evolution tree to be an optional Int, this was how that information had to be handled(at least in swift).

```
enum LevelsUnion: Codable, Hashable {
    case enumeration(LevelsEnum)
    case integer(Int)

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let x = try? container.decode(Int.self) {
            self = .integer(x)
            return
        }
        if let x = try? container.decode(LevelsEnum.self) {
            self = .enumeration(x)
            return
        }
        throw DecodingError.typeMismatch(LevelsUnion.self, DecodingError.Context(codingPath: decoder.codingPath, debugDescription: "Wrong type for LevelsUnion"))
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .enumeration(let x):
            try container.encode(x)
        case .integer(let x):
            try container.encode(x)
        }
    }
}
```

**Comment by maael** [comment]
I'm glad I could help! I hope the app you make goes well, definitely let me know when you release it. And let me know if I can do anything to help, or if there's some info you'd like that this API doesn't give you yet, or if it's hard to get out and you have to do a lot of work to get what you want from it.

Ideally I want the data served by the API to be as easy to consume as possible, so it isn't selfish at all, any improvements to the data shapes and types are excellent to have!

### Unknown Type

I think I will leave this as is (with `[]` meaning no type information at all from the data from the wiki, and `["Unknown"]` explicitly marking it as unknown, in a similar way to how the Wiki does it.

### Empty Values

I'm still not sure on the empty string vs null, but I recently added a way of traversing all values in data objects before saving them, so I could quite easily change it to cast `''` to `null` at any point. For now I'll close this I think, but if it's a huge issue, please re-open the issue to let me know I made a mistake! 😄 

### Evolution Level

Thanks for the feedback! Without people like you making comments and using this too, I'd only improve things as I need them or run into them myself.
