### ISSUE TITLE
Question about how /api/weakness/calculate works.

### ISSUE THREAD

**Issue by Armani96** [maael/temtem-api#102]
Hello,

I was gonna make an application to see the weaknesses of Tem's faster. To do this I believe I need this API endpoint.
Can someone please tell me how I would use this endpoint?

**Comment by maael** [comment]
Hey there, thanks for checking out the API! You can use the endpoint by sending query parameters with the attacking type, and the defending types as a comma separated list. So for example: https://temtem-api.mael.tech/api/weaknesses/calculate?attacking=Electric&defending=Crystal,Toxic.

That will give you some JSON data that looks like this:

```
{
  "attacking":"Electric",
  "defending":[
    "Crystal",
    "Toxic"
  ],
  "modifiers": [
    0.5,
    1
  ],
  "result":0.5
}
```

`modifiers` is the multiplier for the attacking type into each defending type individually, and `result` is the overall modifier that will be used, essentially all of `modifiers` multiplied together.

Hopefully that helps! Let me know if there's any more questions, or if your question is answered go ahead and close the issue!

**Comment by Armani96** [comment]
Thank you so much!
