### ISSUE TITLE
'Conditions' endpoint retrieves wrong icon path for invogorated

### ISSUE THREAD

**Issue by HimmDawg** [maael/temtem-api#109]
So, when you retrieve all conditions from "https://temtem-api.mael.tech/api/conditions", then the "icon" property doesn't point to the correct path on the server.
The retrieved path points to: "https://temtem-api.mael.tech/images/icons/conditions/Invigorated.png"
But through some testing, I found out that it actually points to: "https://temtem-api.mael.tech/images/icons/conditions/Vigorized.png"

**Comment by maael** [comment]
Hey, thanks for pointing this out! This is the one case where the condition name doesn't match the icon name on the wiki! I've added a special case for this when collecting the data for conditions in https://github.com/maael/temtem-api/pull/112, so it should be correct now. 👍 I'm going to go ahead and close this, and if you find any other problems please open a new issue.
