### ISSUE TITLE
Random technique type mistake? -> Possible Capitalization issues in the future.

### ISSUE THREAD

**Issue by ToddGeorgeKelly** [maael/temtem-api#12]
mental vs Mental (First letter isn't capitalized.)

Hey my decoder was being mean to me today and I realized that it was because of this very isolated mistake on the technique "Psychosis". Cant find another instance of this happening, it's not really a problem since it can be fixed on my end through a safety filter of sorts, but just thought I would bring it up.

On the actual website itself, they have it lowercased and I will submit a report to have that fixed there as well. However, it does bring to light a possible improvement on the API's end in that the API could compensate for future errors that wiki contributors might make in capitalization. I suggest that, programmatically, the API should just ensure that all types are set as lowercased or Capitalized, otherwise it may cause problems in the future(Again, not big ones, just lil ones!)

```
{
    "name": "Psychosis",
    "wikiUrl": "https://temtem.gamepedia.com/Psychosis",
    "type": "mental",
    "class": "Status",
    "damage": 0,
    "staminaCost": 0,
    "hold": 3,
    "priority": "unknown",
    "synergy": "None",
    "synergyEffects": [],
    "targets": "?",
    "description": "Apply a 4 Turn Doom Counter on the Target."
  },
```

**Comment by maael** [comment]
Hi, thanks for reporting this, and as always thanks for using it and helping me to improve it, the feedback is great.

I'm a fan of trying to make this as resilient as possible against odd wiki data, so I've changed it so when the api collects anything for a field name `type`, that the data of when lowercased matches a known type name in lowercase, it will replace it with the tidier version that has its first letter capitalised. I opted for this over replacing them with lowercase as it was a change that touched fewer things, and also icons are currently capitalised. Let me know if you think totally lowercase would be better though!

I've refreshed the data too, which fixes the Psychosis case! Sorry about the decoder meanness, and hopefully it isn't as mean now! 😄
