### ISSUE TITLE
Chromeon techniques by levelling

### ISSUE THREAD

**Issue by OniSensei** [maael/temtem-api#120]
The api with https://temtem-api.mael.tech/api/temtems?names=Chromeon
Shows 115 entries for techniques listed by Levelling where it is only supposed to be 10.

**Comment by maael** [comment]
Hey @OniSensei! Chromeon has subspecies depending on the type, each with their own techniques available through levelling, you can see on the wiki page for it [here](https://temtem.fandom.com/wiki/Chromeon). I hope that explains it!

**Comment by maael** [comment]
I'm going to close this, as it's techniques per subspecieis type, and so is intended. If you think otherwise, please let me know!
