### ISSUE TITLE
All technique courses are 'TC001' in the /temtems route (whatever its called)

### ISSUE THREAD

**Issue by BenMasel** [maael/temtem-api#125]
The title says it all xD

**Comment by maael** [comment]
Hey, this was likely related to https://github.com/maael/temtem-api/issues/133, and the wiki format changing causing techniques to be messed up.

Today I've pointed to the new wiki as a data source, and the techniques seem to be collected and reporting correctly in the API, including the temtem route.

![chrome_DB08iXGLyg](https://user-images.githubusercontent.com/5610674/190913786-cffc82db-83e8-4dfe-aa7e-82ec0c80d2ab.png)

I'm going to mark this as closed, but please re-open if you feel it isn't.
