### ISSUE TITLE
Suggestion: Add TC numbers to the technique list

### ISSUE THREAD

**Issue by ToddGeorgeKelly** [maael/temtem-api#14]
Another thing that could be helpful is if the Techniques that were marked as "Training Courses" in the technique list could contain the TC numbers. That data is found on the wiki here:

[Link to TC numbers](https://temtem.gamepedia.com/Training_Course)

Maybe it could either include that data in the technique information itself. ORRRR something that might actually be super useful is if it wasn't included in the technique data, but instead was included in a separate file called Training Courses and was stored as a dictionary with the technique name as a key. This would(as far as I understand) not be inferior since accessing info via a dictionary is fast af.

OOORRRR maybe just do both? Do what ever, honestly, you make good decisions haha and I trust you.

**Comment by maael** [comment]
Hey again, thanks for the suggestion!

I opted to do two things:

1. Add the `/api/training-courses` endpoint in 2939b527612017ca5fbc03453ae88f5077f11a12. The data under it looks something like this:

```json
[{
    "number": "TC001",
    "technique": "Tsunami",
    "type": "Water",
    "location": "Complete Gone with the Sillaro. Requires the Surfboard.",
    "locationType": "quest"
  },
  {
    "number": "TC002",
    "technique": "Stone Wall",
    "type": "Earth",
    "location": "Windward Fort prison floor, cell in the water. Requires the Surfboard.",
    "locationType": "found"
  }]
```

2. In fe63bb4dbecee18b8599aa14d96c8d74e36a98ac I made it so the `/api/temtems` endpoint can take a `expand` query parameter for a number of fields in the past, including techniques. Now, if you do `/api/temtems?expand=techniques`, the API will fill out all the technique data, including adding training course information on a `trainingCourse` key with an item in the same shape as what you'd get a list of from `/api/training-courses`.

I decided to do it this way, as the dictionary approach, while good for looking up, isn't common convention, and makes it more difficult if for example someone wanted to just display a list of all available training courses. But doing the endpoint as a list, and allowing it to be added by the API where most people would want it, hopefully it achieves what we want.

What do you think?

**Comment by ToddGeorgeKelly** [comment]
Looks good to me!
