### ISSUE TITLE
api/ dyes wrong format

### ISSUE THREAD

**Issue by xTiborius** [maael/temtem-api#17]
Hi,

api/dyes has a wrong format
"wikiImageUrl": "https:://

br Tibor

**Comment by maael** [comment]
Hi, thanks for the feedback!

My bad, that was just a typo on my end, I've fixed that now in 093a7ca06aa1cead1032654999befd3d82b6961b, and it's just been deployed now, and the API response `/api/dyes` looks correct.

I'll close this now but please reopen if there is still an issue with this, or open a new issue if you run into anything else!
