### ISSUE TITLE
[data: temtem][question]

### ISSUE THREAD

**Issue by xTiborius** [maael/temtem-api#21]
Under "evolution" there is the item "stage". What does it stand for exactly?
At first I thought it indicated the number of stages of evolution. But since it always says 1, it can't be.

   "evolution": {
      "stage": 1,
      "evolutionTree": [

**Comment by maael** [comment]
Hey there. Good question! That stage field shouldn't be there! It's meant to be on the items in the evolution tree. I'll go ahead and remove it now.

**Comment by xTiborius** [comment]
thx for the info

**Comment by maael** [comment]
No problem, if you have any more questions just let me know!
