### ISSUE TITLE
[question][data:temtem] Routes and Landmarks

### ISSUE THREAD

**Issue by xTiborius** [maael/temtem-api#22]
Hi,

would it be possible to separate the landmark from the route?

Row1Route = Prasine Coast
Row1RouteNote = Second large patch of Grass

br Tibor

**Comment by maael** [comment]
Hey, thanks for the idea!

As the current field for the combined version of this (`location`) is used in some of my own projects, I opted to break this information out into new `place` and `note` fields, so now it'll look like this:

```json
"locations": [
  {
    "location": "Prasine Coast, Second large patch of Grass",
    "place": "Prasine Coast",
    "note": "Second large patch of Grass",
    "island": "Deniz",
    "frequency": "40%",
    "level": "2-4"
  },
  {
    "location": "Prasine Coast, Third large patch of Grass",
    "place": "Prasine Coast",
    "note": "Third large patch of Grass",
    "island": "Deniz",
    "frequency": "40%",
    "level": "3-5"
  }
]
```

I think that adds what you want, so I'll close this for now. If I'm wrong, and you wanted something different,  please reopen the issue!
