### ISSUE TITLE
[question] incubation period of the eggs

### ISSUE THREAD

**Issue by xTiborius** [maael/temtem-api#28]
Hi,
do you happen to know the calculation for the incubation period of eggs?

br Tiborius

**Comment by maael** [comment]
I don't know it I'm afraid, I know it's supposed to be related to the catch rate somehow (higher catch rate = shorter hatch time), but that's it. If you find out I'd be interested to know it so I can add the information to the API.

**Comment by maael** [comment]
Hey, just to let you know, this has now been added as the `hatchMins` field on temtem.

**Comment by TiboriusDev** [comment]
Hey,
thank you for notifying me.
The value indicates the duration of incubation in minutes?

br Tibor

Am So., 31. Mai 2020 um 10:20 Uhr schrieb Matthew Elphick <
notifications@github.com>:

**Comment by TiboriusDev** [comment]
Found the link in the readme^^.
Question answered.

Am So., 31. Mai 2020 um 10:31 Uhr schrieb Tibor Stachoske <
tibor.stachoske@gmail.com>:
