### ISSUE TITLE
Full Body Render

### ISSUE THREAD

**Issue by lauridskern** [maael/temtem-api#32]
Hi, someone made full-body renders of every TemTem. Could you expose those in the API. Maybe even the animated GIFs he provided as well. ☺️

**Comment by maael** [comment]
Hi, thanks for the suggestion!

I've added the paths to the `https://temtem-api.mael.tech/api/temtems` endpoint, with these new fields:

```
    "renderStaticImage": "/images/renders/temtem/static/Swali.png",
    "renderStaticLumaImage": "/images/renders/temtem/luma/static/Swali.png",
    "renderAnimatedImage": "/images/renders/temtem/animated/Swali.gif",
    "renderAnimatedLumaImage": "/images/renders/temtem/luma/animated/Swali.gif"
```

And here's the example images from served from https://temtem-api.mael.tech:

![static render](https://temtem-api.mael.tech/images/renders/temtem/static/Swali.png "Static Render")
![static luma render](https://temtem-api.mael.tech/images/renders/temtem/luma/static/Swali.png "Static Luma Render")
![animated render](https://temtem-api.mael.tech/images/renders/temtem/animated/Swali.gif "Animated Render")
![animated luma render](https://temtem-api.mael.tech/images/renders/temtem/luma/animated/Swali.gif "Animated Luma Render")

I think this is done now, so I'll close this, please reopen it if you disagree though!

**Comment by lauridskern** [comment]
Thats awesome! Thank you!
