### ISSUE TITLE
Add larger image for items and gear

### ISSUE THREAD

**Issue by lauridskern** [maael/temtem-api#34]
Thanks for the awesome API and the addition of my last feature request! 
I noticed that the item thumbnail icons are pretty small and that there should be a bigger version for each icon on the wiki. Could you add those?

**Comment by maael** [comment]
Hey!

What makes you think there should be a bigger version of the images?

Here's the icon for Coward's Cloak:

![cowardscloak](https://temtem-api.mael.tech/images/icons/gear/CowardsCloak.png)

Which is 221x173 pixels.

You can see on the wiki that this is the same size as what they have [here](https://temtem.gamepedia.com/File:Coward%27s_Cloak.png).

**Comment by lauridskern** [comment]
Sorry gear seems to be fine but Items only return a 75x75 image thumbnail.

**Comment by maael** [comment]
Correct me if I'm wrong, but the api doesn't actually return any images for items at the moment? It just gives a link to the wiki image, that shouldn't really be used for hot linking anyway?

The better solution is to get the item images and put them in the api.

**Comment by lauridskern** [comment]
yeah it returns the wiki link. that would probably be a better solution, true

**Comment by maael** [comment]
Hey, thanks for the suggestion!

Items now have a `icon` field that is the relative path to the icon on the API, and they are a larger size, here's an example:

![HugeCrystalIcon](https://temtem-api.mael.tech/images/icons/items/HugeCrystalIcon.png)

**Comment by lauridskern** [comment]
awesome!! You are so fast, thank you!

**Comment by lauridskern** [comment]
Small suggestion, the same would work for "cosmetics" and "dyes" as well.
