### ISSUE TITLE
Saipark info collection broken

### ISSUE THREAD

**Issue by maael** [maael/temtem-api#35]
Looks like the layout was changed. Last update to the api data was June 8th.

https://temtem-api.mael.tech/api/saipark

https://temtem.gamepedia.com/Saipark

**Comment by TiboriusDev** [comment]
Since last week there are no more data.

**Comment by maael** [comment]
This is now fixed: https://github.com/maael/temtem-api/blob/master/data/saipark.json

I'll close this, reopen it if you think there's still an issue.
