### ISSUE TITLE
No "steps" in quests

### ISSUE THREAD

**Issue by TiboriusDev** [maael/temtem-api#37]
https://temtem.gamepedia.com/Adventure_in_the_Myrisles

{"name":"Adventure in the Myrisles",
"wikiUrl":"https://temtem.gamepedia.com/Adventure_in_the_Myrisles",
"type":"main",
"steps":[],
"rewards":["Elevator key","Signed Authorization","Belsoto grunt uniform","Crystal skates","Anahir","Deendre"],
"startingLocation":"Nanga",
"startingNPC":"",
"requirements":""}

**Comment by maael** [comment]
Fixed in 7f30ca8386b3e98db68d053d492e3d27d791627e, they changed to start using a better list format. Now it will try the original detection, and if that fails, it will try detecting with the newer format.
