### ISSUE TITLE
Add level to learn techniques of species

### ISSUE THREAD

**Issue by Trobiun** [maael/temtem-api#4]
It's a simple suggestion, I think it can be useful to know in which level species will learn techniques by leveling.

**Comment by maael** [comment]
Hiya, thanks for the idea and opening an issue! I've added this now, it will be available as the `levels` property on techniques where their type is `Levelling`. I will update the site example to show this, and it should be available from the API itself shortly.

**Comment by maael** [comment]
This is now available at https://temtem-api.mael.tech/api/temtems and is shown in the example at https://temtem-api.mael.tech/#/api/temtems (might need a hard refresh to show up though to stop any caching).
