### ISSUE TITLE
All temtem portrait and render urls append "scale-to-width-" and don't work

### ISSUE THREAD

**Issue by lauridskern** [maael/temtem-api#41]

**Comment by maael** [comment]
@lauridskern you should use the ones from the API itself - don't hotlink to the wiki ones. I do not control those and they may change.

The following fields provide the path to the images available on the temtem-api itself: `icon`, `lumaIcon`, `renderStaticImage`, `renderStaticLumaImage`, `renderAnimatedImage`, `renderAnimatedLumaImage`.

**Comment by maael** [comment]
I've fixed this now [here](https://github.com/maael/temtem-api/commit/76948672ba91cf9d32cea19814580ae8d7cead42) but please change to use the fields I listed there, for images from the api itself, don't hotlink to the wiki directly.

**Comment by lauridskern** [comment]
Icons, gear and cosmetics have the same problem apparently and don't provide an API path yet. Would you mind fixing it until API paths are provided? :)

**Comment by maael** [comment]
Hey @lauridskern, can I ask you to make a new issue for any new requests please, don't necro different old issues, so I can track things more easily, as I just do this in my free time! 😅  Take a look and check if there's any other things that need icons and make an issue for them, and check existing issues in the future too please, for example there's already 2 existing relevant issues:

- [Here's one for cosmetic icons](https://github.com/maael/temtem-api/issues/40)
- [Here's one for dye](https://github.com/maael/temtem-api/issues/39)

**Comment by lauridskern** [comment]
Sorry I thought this was relevant to this issue because of the wiki path not working. Will do next time
