### ISSUE TITLE
Missing techniques

### ISSUE THREAD

**Issue by Articuno-I** [maael/temtem-api#43]
Hi!

I was looking at using the data available in `data/techniques.json` rather than writing my own wiki scraper for my [python temtem library](https://github.com/Articuno-I/TemTem). However, I noticed that these techniques seem to be missing:
```
Wind Blade
Water Blade
Wind Burst
Water Cannon
Water Cutting Lily
```
(Note that my data is probably missing some post-Kisiwa techniques, hence why I was going to write a scraper myself, so this may not be a complete list of missing techniques).

I guess something about those two types specifically (Wind and Water) at the start of the name is breaking the scraper in some way? I saw techniques like `Toxic Fang` are in your data, as is `High-pressure Water`.

I took a brief look at the traits data and couldn't see anything missing there, despite having some names like `Water Affinity` and `Toxic Skin`, so I'd guess this is only affecting Techniques.

**Comment by maael** [comment]
I've hunted down the issue and it's actually because, with the new techniques from the new island, there's now two pages of them on the wiki. The scraper here only scrapes the first page, as there was only one page when I originally did it.

**Comment by maael** [comment]
@Articuno-I the techniques now collect from all available pages - you can see the fix along with the extra techniques being added in https://github.com/maael/temtem-api/commit/db303bcf8c845ab81e9fa2423cff2da0a872118d. 👍 This fixes the issue so I'll go ahead and close this. Reopen it if you think there's still an issue.
