### ISSUE TITLE
Inflicting condition

### ISSUE THREAD

**Issue by TybaIt** [maael/temtem-api#44]
would be nice to know what status effect is applied.

https://temtem.gamepedia.com/Cold_Breeze
the ``effect`` line

it's much easier and more reliable to find the applied effect rather than in the ``description``

Add effect field to a techniques' main effect

**Comment by maael** [comment]
This is done in https://github.com/maael/temtem-api/commit/ffec44ad1fe77016612d72c43e93446c0972f172.

For example, Acid Reflux now looks like:

```json
  {
    "name": "Acid Reflux",
    "wikiUrl": "https://temtem.gamepedia.com/Acid_Reflux",
    "type": "Toxic",
    "class": "Special",
    "classIcon": "/images/icons/technique/Special.png",
    "damage": 80,
    "staminaCost": 20,
    "hold": 2,
    "priority": "normal",
    "priorityIcon": "/images/icons/priority/normal.png",
    "synergy": "None",
    "synergyEffects": [
      
    ],
    "targets": "Other Team or Ally",
    "description": "Toxolotl draws from the Toxic essence of Xolot, moderately damaging and Poisoning the whole team for 2 turns.",
    "effectText": "Acid Reflux deals damage to the opposing team or the user's ally and inflicts the Poisoned Condition for 2 turns.",
    "effects": [
      {
        "type": "condition",
        "turns": 2,
        "condition": "Poisoned"
      }
    ]
  },
```

I think this adds what you've suggested - so I'll mark this as closed. If you disagree, feel free to open it again, and let me know what I've missed. 👍

**Comment by TybaIt** [comment]
Ah, thanks a lot!

**Comment by TybaIt** [comment]
Ah, I think entries in the effects array still need a "target" field because it can happen that the Move itself targets the other team but at the same time a condition like "Evading" is self-applied. 
So an effect entry may benefit from a target field as well:
Values for it would be:
``
"All",
"Self",
"Ally",
"Team",
"Other Team",
default: "Target"``

default would be ``Target``. The other values make the condition independent of the moves actual target. Don't know if moves like that already exist but they can in the future.
