### ISSUE TITLE
Add ``fields`` param to api/patches

### ISSUE THREAD

**Issue by TybaIt** [maael/temtem-api#46]
https://temtem-api.mael.tech/api/patches

I am just interested in the fields ``version`` and ``date`` because I will use these values to check for oudated resources.

**Comment by maael** [comment]
Totally possible to add the fields limits - but those fields aren't too useful to use as a source of resource freshness, as the content it pulled from the wiki, and is continually updated between patches too. If anything you'd be better off just caching and refreshing every 4 hours, as the api only updates every 4 hours.

**Comment by TybaIt** [comment]
On the users local machine I definitely do not want to update every 4 hours.
What I do is caching all resources locally and never refresh again until a patch hits.

**Comment by maael** [comment]
But the data doesn't get updated when the patch hits, and we get the patch info a separate place from the actual game data, as the data is updated by users on the wiki. So the timeline is more like:

```
[Patch hits] 
-> [Temtem website updated] 
-> [Temtem API here picks up the new version and lists it] 
-> [Players play and explore new patch and add data to wiki] 
-> [Temtem API here picks up data changes and lists it]
```

So if you cache and only update based on the **patch time** then your data will be permanently behind a patch of what it thinks it is, as the information that there's a new patch lands in the api before the patch data itself, if that makes sense?

What you really want to know is if the data the API exposes has changed. That will be possible via the `/api/summary` endpoint (it's currently being added, and will become available shortly), which exposes the data [here](https://github.com/maael/temtem-api/blob/master/data/summary.json) and looks something like this:

```json
{
  "mostRecent": "2020-09-24T04:02:50.065Z",
  "dataStats": [
    {
      "mtime": "2020-08-27T08:01:49.919Z",
      "name": "weaknesses"
    },
    {
      "mtime": "2020-02-01T04:01:05.614Z",
      "name": "types"
    },
    {
      "mtime": "2020-09-23T20:02:42.338Z",
      "name": "traits"
    },
    {
      "mtime": "2020-07-29T12:01:52.926Z",
      "name": "trainingCourses"
    },
    {
      "mtime": "2020-09-24T00:03:05.421Z",
      "name": "techniques"
    },
    {
      "mtime": "2020-09-21T08:04:14.715Z",
      "name": "saipark"
    },
    {
      "mtime": "2020-09-03T20:01:58.774Z",
      "name": "quests"
    },
    {
      "mtime": "2020-09-23T12:02:59.373Z",
      "name": "patches"
    },
    {
      "mtime": "2020-09-24T04:02:50.065Z",
      "name": "locations"
    },
    {
      "mtime": "2020-09-24T00:03:05.421Z",
      "name": "knownTemtemSpecies"
    },
    {
      "mtime": "2020-09-23T20:02:42.338Z",
      "name": "items"
    },
    {
      "mtime": "2020-09-22T16:02:36.722Z",
      "name": "gear"
    },
    {
      "mtime": "2020-04-18T00:01:19.424Z",
      "name": "freetemRewards"
    },
    {
      "mtime": "2020-09-01T00:02:17.397Z",
      "name": "dyes"
    },
    {
      "mtime": "2020-09-19T16:02:50.482Z",
      "name": "cosmetics"
    },
    {
      "mtime": "2020-08-22T08:06:45.211Z",
      "name": "conditions"
    },
    {
      "mtime": "2020-08-08T12:01:33.301Z",
      "name": "characters"
    }
  ]
}
```

Where the top level `mostRecent` field is the most recent time _any_ of the data files was changed, and the `mtime` on each item in `dataStats` is the modified time for the specific data files. This information should allow you to cache resources much better, while ensuring your users have access to the patch data.

Hopefully that all makes sense.

I've also enabled the `fields` param for `/api/patches`, as well as a number of other endpoints that were missing it. I also added the `limit` param, so you can limit the max number of results returned. Again, these are currently being added, and will become available shortly. You can see where they've been added by checking the docs at https://temtem-api.mael.tech.
