### ISSUE TITLE
saipark.json dateRange

### ISSUE THREAD

**Issue by TiboriusDev** [maael/temtem-api#62]
Hi,
can you remove the [edit] out of the dateRange?
```
"dateRange": "August 24th to August 30th, 2020[edit]",
"dateRange": "September 28th to October 4th, 2020[edit | edit source]",
```
and the stats are no longer correct
```
"lumaRate": 50,
"minSvs": 3,
```
Tibor

**Comment by maael** [comment]
The `[edit]` etc text is no longer there, and the data collection/incorrect stats will be tracked over in https://github.com/maael/temtem-api/issues/35#issuecomment-717987008 so I'll close this issue.
