### ISSUE TITLE
weaknesses.json has wrong data

### ISSUE THREAD

**Issue by TiboriusDev** [maael/temtem-api#65]
weaknesses.json has wrong data

**Comment by maael** [comment]
Hi - it would be great to know exactly what is wrong, besides "wrong", so I can look into it further, thanks.

**Comment by TiboriusDev** [comment]
In the json the wind is at neutral at 0.5
In the wiki is mental 0.5

**Comment by maael** [comment]
this has been fixed, the wiki changed the ordering on their table which messed up the collection, I'll close this, please reopen if there's still an issue
