### ISSUE TITLE
Technique target data missing

### ISSUE THREAD

**Issue by Articuno-I** [maael/temtem-api#66]
The "targets" field has been left empty for every entry in data/techniques.json as of d623afc9c691194d66d12da10fb0a42b48e8848a.

I see the data is still available on the wiki, in what looks like the same spot, but I don't see a non-automated commit immediately before this issue, so I don't know whether this was caused by a change in the wiki or scraping code.

**Comment by maael** [comment]
Thanks for reporting this, they changed the names and layouts of things in the info boxes for techniques, which caused this. I've fixed it now, so I'll close this. Please reopen if you think there's still an issue.
