### ISSUE TITLE
Feature Request: Dojos

### ISSUE THREAD

**Issue by BaileyMillerSSI** [maael/temtem-api#69]
Similar to the TemTem endpoint could the api include an endpoint for Dojo data? There is a lot of data to display but minimally I'd like the name of the dojo, the leader, and the temtems that leader uses in order.

**Comment by maael** [comment]
Hi! 

Thanks for the suggest - I've gone ahead and added the basics of dojo information has now been added at https://temtem-api.mael.tech/api/dojos, for the 5 available dojos. You can read more about it on the docs site at https://temtem-api.mael.tech/#/api/dojos. In regards to the "order" used, it returns the order on the wiki - which I hope is what you were wanting!

An example of the returned data is:

```json
[
  {
    "name": "Arissola Dojo",
    "wikiUrl": "https://temtem.gamepedia.com/Arissola_Dojo",
    "types": ["Wind", "Water"],
    "leader": {
      "name": "Sophia",
      "temtem": [
        {
          "level": 17,
          "name": "Kalabyss",
          "number": 128,
          "trait": "Botanophobia",
          "techniques": [
            "Aqua Stone",
            "Strangle",
            "Water Blade",
            "Tentacle Whip"
          ]
        },
        {
          "level": 17,
          "name": "Loali",
          "number": 11,
          "trait": "Botanist",
          "techniques": ["Toxic Spores", "Wind Blade", "Urushiol", "Tenderness"]
        },
        {
          "level": 18,
          "name": "Sparzy",
          "number": 82,
          "trait": "Last Rush",
          "techniques": ["Psychosis", "Tesla Prison", "Held Anger", "DC Beam"]
        },
        {
          "level": 19,
          "name": "Pigepic",
          "number": 141,
          "trait": "Friendship",
          "techniques": ["Heavy Blow", "Nimble", "Nibble", "Scratch"]
        },
        {
          "level": 21,
          "name": "Tuwai",
          "number": 130,
          "trait": "Spoilsport",
          "techniques": [
            "Multiple Pecks",
            "Wind Burst",
            "Feather Gatling",
            "Shrill Voice"
          ]
        },
        {
          "level": 22,
          "name": "Oceara",
          "number": 115,
          "trait": "Hydrologist",
          "techniques": [
            "Ice Shuriken",
            "Tsunami",
            "High-pressure Water",
            "Kick"
          ]
        }
      ]
    }
  },
  ...
]
```

I think that should resolve this specific request, so I'm going to close the issue now. If you think there's more that needs to be done, please feel free to either re-open this, or raise a new issue. 👍

**Comment by BaileyMillerSSI** [comment]
That was so fast! I am very busy at work this week but I was hoping to eventually open source my code so you can see how I am using these features and the roadmap for the bot I am building. 
[Alpha Page](https://discord.baileymiller.dev/)
