### ISSUE TITLE
no locations in knownTemtemSpecies.json

### ISSUE THREAD

**Issue by TiboriusDev** [maael/temtem-api#70]
In the "knownTemtemSpecies.json" the locations where the tem's can be found are no longer recorded.

**Comment by maael** [comment]
They changed something to do with the locations table on temtem pages that means temtem's locations aren't picked up at the moment. It will need some changes in the web scraper to fix.

**Comment by maael** [comment]
This is fixed now in https://github.com/maael/temtem-api/commit/c4e84dc86bda6b3466c248b621a18ccb7afb2a18, and will be fixed in future collections of data. As it's fixed I'm going to close this - reopen the issue if you think there's still a problem, or feel free to open a new issue.
