### ISSUE TITLE
Reoccurring damage from synergy effects

### ISSUE THREAD

**Issue by ToddGeorgeKelly** [maael/temtem-api#9]
Hey this is an awesome database, was playing around with it and found that on moves like "Urushiol" that have reoccurring damage from poison, the API is displaying this as 4 extra damage rather than poison damage for 4 turns.

**Comment by maael** [comment]
Hey, thanks for the comment!

At the moment the technique synergy info is a bit hit and miss for sure, there's a comment [here](https://github.com/maael/temtem-api/blob/master/scripts/data/embellishTechniques.ts#L103-L110) outlining most of the cases I haven't taken care of yet. I'll try to get it fixed ASAP!

**Comment by ToddGeorgeKelly** [comment]
I apologize that I didn't see that beforehand. I will keep an eye out for anything else I run into! Thanks so much!


( I do hope that I do not come off as critical haha. Your API has been crazy helpful to me. I wanted to make an app just for fun and your data is the best source out there rn. )

**Comment by maael** [comment]
@ToddGeorgeKelly Not critical at all, it's useful for me to get other peoples feedback, thanks for taking the time to use the API and let me know your thoughts.

Just as a heads up - this has now been resolved, and technique synergy information is much more uniform, and actual contains all the information now.

The change is that the `SynergyEffect` and `SynergyDamage` fields have been removed from techniques.

Now instead, there is the `SynergyEffects` key, which contains an array of objects of the following shape:

```json
{
  "effect": "Effect description",
  "type": "damage",
  "damage": 0
}
```

The current possible values for `type` are:
| Type |
| ----- |
| damage |
| buff |
| debuff |
| condition |
| priority |
| unknown |

`damage` will be `0` for anything not of `damage` type.

Hopefully that all makes sense, and seems like a good solution. Let me know what you think!
