### ISSUE TITLE
"techniques" empty on temtem data

### ISSUE THREAD

**Issue by TiboriusDev** [maael/temtem-api#90]

**Comment by arossetter** [comment]
@maael I just happened to be looking at this yesterday. Put up a pull request to address:
https://github.com/maael/temtem-api/pull/91

**Comment by maael** [comment]
Thanks for the PR above, the techniques were picked up again, an committed in c2ca2c79ffa2ed4b698514e76f5cbd982d894404. I'll mark this as closed now, please feel free to re-open it if you think there's still an issue. And thanks again @arossetter for fixing it. 🎉
