### ISSUE TITLE
/api/dojos Leader->TemTem array is always empty

### ISSUE THREAD

**Issue by BaileyMillerSSI** [maael/temtem-api#93]
The temtem array from the /dojo endpoint is returning empty.

**Comment by BaileyMillerSSI** [comment]
Found with commit d3b37c9ce88a9a7fabfda772fa1fa38f9dae6e19

**Comment by maael** [comment]
Probably due to some changes on the wiki around how the data is structured, which means it isn't getting picked up at the moment as it's not in the format it used to be. Feel free to take a look into it, fixes are always welcome, or else I will get around to this at some point. 👍

**Comment by BaileyMillerSSI** [comment]
I can try to take a look at it this weekend, I haven't pulled this code locally in a bit 😂

**Comment by maael** [comment]
Thanks for reporting this! Fixed in db14da97c17148793836c47bc3f4e21b17676e3e, so I'm going to mark this as closed, but let me know if you have any more issues, either re-open this or open a new issue!

**Comment by maael** [comment]
Fixed another minor issue in that fix that meant only the last technique was listed for each temtem, fixed in 536335ab39b611f740273e9ec92bded45aba9ffe.

**Comment by BaileyMillerSSI** [comment]
@maael 
I am getting some weird data back from the /dojo endpoint again. Specifically, I am seeing dojos called Melee and Mental as well as Dr. Sasaya has an empty temtem array.

**Comment by maael** [comment]
Hi @BaileyMillerSSI instead of commenting on a closed issue, could you raise a new one please? It's probably another separate issue due to a wiki change. Thanks.
